<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AuthApplication\Module'                        => __DIR__ . '/Module.php',
    'AuthApplication\Controller\IndexController' => __DIR__ . '/src/AuthApplication/Controller/IndexController.php',
    'AuthApplicationTest\Framework\TestCase'        => __DIR__ . '/tests/AuthApplication/Framework/TestCase.php',
    'AuthApplicationTest\SampleTest'                => __DIR__ . '/tests/AuthApplication/SampleTest.php',
);
