<div class="container">
<div class="row">
<div class="control-group">
<div class="controls">
<?php
if (!empty($this->successMessages)) {
	foreach ($this->successMessages as $msg) {
		?>
                                    <div class="alert alert-success alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <?= $msg; ?>
                                    </div>
                                <?php
                                }
                            }
                            if (!empty($this->errorMessages)) {
                                foreach ($this->errorMessages as $msg) {
                                    ?>
                                    <div class="alert alert-error alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <?= $msg; ?>
                                    </div>
                                <?php
                                }
                            }
                            ?>
                    </div>
             </div>
        </div>
        <div class="row">
            <div class="span6 offset3 well">
        	<h3><?php echo $this->translate('User Password Manage');?></h3>
        	<?php
                $editForm->prepare();
                $editForm->setAttribute('action', $this->url('auth-user/default',array('action'=>'changepassword','id'=>$this->idUser)));
                $editForm->setAttribute('method', 'POST');
                $password = $editForm->get('PASSWORD');
                $verify_password = $editForm->get('PASSWORD_VERIFY');
                $submit = $editForm->get('submit');
                ?>
                  <?php echo $this->form()->openTag($editForm);
                                ?>
                                <table>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($password); ?>
                                	               <?php echo $this->formInput($password); ?>
                                	               <?php echo $this->formElementErrors($password); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($verify_password); ?>
                                	               <?php echo $this->formInput($verify_password); ?>
                                	               <?php echo $this->formElementErrors($verify_password); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td><?php echo $this->formSubmit($submit);?></td>
                                		</tr>
                                </table>
                                <?php echo $this->form()->closeTag(); ?>
                            </div>
                      </div>
                </div>