<div class="container">
        <div class="row">
             <div class="control-group">
                       <div class="controls">
                            <?php
                            if (!empty($this->successMessages)) {
                                foreach ($this->successMessages as $msg) {
                                    ?>
                                    <div class="alert alert-success alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <?= $msg; ?>
                                    </div>
                                <?php
                                }
                            }
                            if (!empty($this->errorMessages)) {
                                foreach ($this->errorMessages as $msg) {
                                    ?>
                                    <div class="alert alert-error alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <?= $msg; ?>
                                    </div>
                                <?php
                                }
                            }
                            ?>
                    </div>
             </div>
        </div>
        <div class="row">
            <div class="span6 offset3 well">
        	<h3><?php echo $this->translate('Registration Details');?></h3>
        	<?php
                $registerForm->prepare();
                $registerForm->setAttribute('action', $this->url('auth-user/default',array('action'=>'register')));
                $registerForm->setAttribute('method', 'POST');
                $username = $registerForm->get('USERNAME');
                $firstname = $registerForm->get('FIRSTNAME');
                $lastname = $registerForm->get('LASTNAME');
                $email = $registerForm->get('EMAIL');
                $phone = $registerForm->get('PHONE');
                $picture = $registerForm->get('PICTURE');
                $password = $registerForm->get('PASSWORD'); //PASSWORD_VERIFY
                $password_verify = $registerForm->get('PASSWORD_VERIFY');
                $submit = $registerForm->get('submit');
                ?>
                  <?php echo $this->form()->openTag($registerForm);
                                ?>
                                <table>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($username); ?>
                                	               <?php echo $this->formInput($username); ?>
                                	               <?php echo $this->formElementErrors($username); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($firstname); ?>
                                	               <?php echo $this->formInput($firstname); ?>
                                	               <?php echo $this->formElementErrors($firstname); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($lastname); ?>
                                	               <?php echo $this->formInput($lastname); ?>
                                	               <?php echo $this->formElementErrors($lastname); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($email); ?>
                                	               <?php echo $this->formInput($email); ?>
                                	               <?php echo $this->formElementErrors($email); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($phone); ?>
                                	               <?php echo $this->formInput($phone); ?>
                                	               <?php echo $this->formElementErrors($phone); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($password); ?>
                                	               <?php echo $this->formInput($password); ?>
                                	               <?php echo $this->formElementErrors($password); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($password_verify); ?>
                                	               <?php echo $this->formInput($password_verify); ?>
                                	               <?php echo $this->formElementErrors($password_verify); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($picture); ?>
                                	               <?php echo $this->formFile($picture); ?>
                                	               <?php echo $this->formElementErrors($picture); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td><?php echo $this->formSubmit($submit);?></td>
                                		</tr>
                                </table>
                                <?php echo $this->form()->closeTag(); ?>
                            </div>
                      </div>
                </div>