<div class="container">
<div class="row">
<div class="control-group">
<div class="controls">
<?php
if (!empty($this->successMessages)) {
	foreach ($this->successMessages as $msg) {
		?>
                                    <div class="alert alert-success alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <?= $msg; ?>
                                    </div>
                                <?php
                                }
                            }
                            if (!empty($this->errorMessages)) {
                                foreach ($this->errorMessages as $msg) {
                                    ?>
                                    <div class="alert alert-error alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-hidden="true">&times;</button>
                                        <?= $msg; ?>
                                    </div>
                                <?php
                                }
                            }
                            ?>
                    </div>
             </div>
        </div>
        <div class="row">
            <div class="span6 offset3 well">
        	<h3><?php echo $this->translate('Blog UI');?></h3>
        	<?php
                $blogForm->prepare();
                $blogForm->setAttribute('action', $this->url('blog/manage',array('action'=>'manage','id'=>$this->id)));
                $blogForm->setAttribute('method', 'POST');
                $title = $blogForm->get('TITLE');
                $content = $blogForm->get('CONTENT');
                $category_id = $blogForm->get('CATEGORY_ID');
                $product_id = $blogForm->get('PRODUCT_ID');
                $submit = $blogForm->get('submit');
                ?>
                  <?php echo $this->form()->openTag($blogForm);
                                ?>
                                <table>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($title); ?>
                                	               <?php echo $this->formInput($title); ?>
                                	               <?php echo $this->formElementErrors($title); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   <?php echo $this->formLabel($content); ?>
                                	               <?php echo $this->formTextarea($content); ?>
                                	               <?php echo $this->formElementErrors($content); ?>
                                	       </td>
                                		</tr>
                                		<tr>
                                			<td>   
                                				  <?php echo $this->formLabel($category_id); ?>
                                	               <?php echo $this->formselect($category_id); ?>
                                	               <?php echo $this->formElementErrors($category_id); ?>
                                	       </td> 
                                		</tr>
                                		<tr>
                                			<td>   
                                				<?php echo $this->formLabel($product_id); ?>
                                	            <?php echo $this->formselect($product_id); ?>
                                	            <?php echo $this->formElementErrors($product_id); ?>
                                	       </td>
                                		</tr>                          
                                		<tr>
                                			<td><?php echo $this->formSubmit($submit);?></td>
                                		</tr>
                                </table>
                                <?php echo $this->form()->closeTag(); ?>
                            </div>
                      </div>
                </div>