<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AclApplication\Module'                        => __DIR__ . '/Module.php',
    'AclApplication\Controller\IndexController' => __DIR__ . '/src/AclApplication/Controller/IndexController.php',
    'AclApplicationTest\Framework\TestCase'        => __DIR__ . '/tests/AclApplication/Framework/TestCase.php',
    'AclApplicationTest\SampleTest'                => __DIR__ . '/tests/AclApplication/SampleTest.php',
);
