<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AclNavApplication\Module'                        => __DIR__ . '/Module.php',
    'AclNavApplication\Controller\IndexController' => __DIR__ . '/src/AclNavApplication/Controller/IndexController.php',
    'AclNavApplicationTest\Framework\TestCase'        => __DIR__ . '/tests/AclNavApplication/Framework/TestCase.php',
    'AclNavApplicationTest\SampleTest'                => __DIR__ . '/tests/AclNavApplication/SampleTest.php',
);
